parser: babel-eslint
extends:
  - airbnb
plugins:
  - react
rules:
  import/no-extraneous-dependencies: 'off'
  object-curly-newline: 'off'
  max-len:
    - error
    - code: 120
      ignoreComments: true
  react/jsx-filename-extension:
    - error
    - extensions:
      - ".js"
  semi:
    - error
    - never
env:
  browser: true
  es6: true
  jasmine: true
globals:
  jest: false
  "$Keys": false
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src
