---
dist: trusty
language: node_js
node_js:
  - 9
cache:
  yarn: true
  directories:
  - node_modules
install: true
stages:
  - install
  - eslint-coverage
  - build
  - name: npm-release
    if: tag =~ ^v(\d{1}).(\d{1}).(\d{1})$
jobs:
  include:
    - stage: install
      script: yarn

    - stage: eslint-coverage
      script: yarn eslint
    -
      script: yarn test:ci
    -
      script: yarn bundle:check

    - stage: npm-release
      node_js: 9
      script: echo "Deploying to npm..."
      deploy:
        provider: npm
        email: "filippo@sarzana.me"
        api_key: $NPM_API_KEY
        gem: travis-build-stages-demo
        on:
          tags: true
