---
dist: trusty
language: node_js
node_js:
  - 9
cache:
  yarn: true
  directories:
  - node_modules
install: true
stages:
  - name: NPM Release
    if: tag =~ ^v(\d{1}).(\d{1}).(\d{1})$
  - name: Github Release
    if: branch = master
jobs:
  include:
    - script: yarn
    - script: yarn eslint
    - script: yarn test:ci
    - script: yarn build
    - script: yarn docs
    - script: yarn bundle:check
    - script: ls ${TRAVIS_BUILD_DIR}/docs

    - stage: NPM Release
      node_js: 9
      script: echo "Deploying to npm..."
      deploy:
        api_key: $NPM_API_KEY
        email: "filippo@sarzana.me"
        gem: travis-build-stages-demo
        provider: npm
        skip_cleanup: true
        on:
          tags: true

    - stage: Github Release
      node_js: 9
      script: echo "Deploying Github Pages..."
      deploy:
        github_token: $GITHUB_TOKEN
        provider: pages
        skip_cleanup: true
        local_dir: ${TRAVIS_BUILD_DIR}/docs
